### ISSUE TITLE
help:ImportError: No module named core

### ISSUE THREAD

**Issue by zhoujw8792** [docker/docker-registry#1048]
root@iZ28zeay8xfZ:/alidata/docker/data/docker-registry# gunicorn -c contrib/gunicorn.py docker_registry.wsgi:application
2015-12-22 12:32:47 [23028] [INFO] Starting gunicorn 0.13.4
2015-12-22 12:32:47 [23028] [INFO] Listening at: http://127.0.0.1:8000 (23028)
2015-12-22 12:32:47 [23028] [INFO] Using worker: sync
2015-12-22 12:32:47 [23031] [INFO] Booting worker with pid: 23031
2015-12-22 12:32:47 [23031] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/gunicorn/arbiter.py", line 456, in spawn_worker
    worker.init_process()
  File "/usr/lib/pymodules/python2.7/gunicorn/workers/base.py", line 100, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/lib/pymodules/python2.7/gunicorn/app/base.py", line 101, in wsgi
    self.callable = self.load()
  File "/usr/lib/pymodules/python2.7/gunicorn/app/wsgiapp.py", line 24, in load
    return util.import_app(self.app_uri)
  File "/usr/lib/pymodules/python2.7/gunicorn/util.py", line 241, in import_app
    **import**(module)
  File "/usr/local/lib/python2.7/dist-packages/docker_registry-1.0.0_dev-py2.7.egg/docker_registry/wsgi.py", line 19, in <module>
    from .app import app  # noqa
  File "/usr/local/lib/python2.7/dist-packages/docker_registry-1.0.0_dev-py2.7.egg/docker_registry/app.py", line 8, in <module>
    from . import toolkit
  File "/usr/local/lib/python2.7/dist-packages/docker_registry-1.0.0_dev-py2.7.egg/docker_registry/toolkit.py", line 18, in <module>
    from docker_registry.core import compat
ImportError: No module named core
2015-12-22 12:32:47 [23031] [INFO] Worker exiting (pid: 23031)
2015-12-22 12:32:48 [23028] [INFO] Shutting down: Master
2015-12-22 12:32:48 [23028] [INFO] Reason: Worker failed to boot.

**Comment by dmp42** [comment]
At least pip install it if you don't want to use the official container. Or python setup.py install

Either way, I strongly encourage you to look into docker/distribution instead.

Hope that helps.

**Comment by zhoujw8792** [comment]
Thanks,I will be try docker/distribution instead
