### ISSUE TITLE
cannot upload image to swift backend

### ISSUE THREAD

**Issue by bacongobbler** [docker/docker-registry#172]
This seems to be an issue with the swift backend. When I try uploading to a container, the image is never uploaded.

For example, when I try to push the `ubuntu` image, this is the log output:

```
$ SETTINGS_FLAVOR=swift ./wsgi.py 
2013-12-27 10:06:53,657 INFO:  * Running on http://0.0.0.0:5000/
2013-12-27 10:06:53,657 INFO:  * Restarting with reloader
2013-12-27 10:06:57,066 ERROR: 127.0.0.1 - - [27/Dec/2013 10:06:57] code 400, message Bad HTTP/0.9 request type ('\x16\x03\x01\x00\x82\x01\x00\x00~\x03\x03R\xbd\xc1\xc1\xf5\xf1%k\xfdW\x0f\x97$\x7f\xf4\xb7=\xafZd\xf3?m\x0e\xada\xf5&j\x9d%\xa8\x00\x00\x1a\xc0/\xc0+\xc0\x11\xc0\x07\xc0\x13\xc0')
2013-12-27 10:06:57,067 INFO: 127.0.0.1 - - [27/Dec/2013 10:06:57] "�~R�����%k�W�$��=�Zd�?m�a�&j�%��/�+����   ��" 400 -
2013-12-27 10:06:57,071 INFO: 127.0.0.1 - - [27/Dec/2013 10:06:57] "GET /v1/_ping HTTP/1.1" 200 -
2013-12-27 10:06:57,075 ERROR: 127.0.0.1 - - [27/Dec/2013 10:06:57] code 400, message Bad HTTP/0.9 request type ('\x16\x03\x01\x00\x82\x01\x00\x00~\x03\x03R\xbd\xc1\xc1\xf1\x8f\xdf\x1a\x16:\xc7\xbd\xd2\xae9\x8d\xb8\xba\xba\xcd\x1b\x949\x8b\xd64\x8f.\x80\xac\x1f\x19\x00\x00\x1a\xc0/\xc0+\xc0\x11\xc0\x07\xc0\x13\xc0')
2013-12-27 10:06:57,075 INFO: 127.0.0.1 - - [27/Dec/2013 10:06:57] "�~R����:ǽҮ9�����9��4���/�+����  ��" 400 -
2013-12-27 10:06:57,078 INFO: 127.0.0.1 - - [27/Dec/2013 10:06:57] "GET /v1/_ping HTTP/1.1" 200 -
2013-12-27 10:06:57,121 INFO: Starting new HTTPS connection (1): region-a.geo-1.identity.hpcloudsvc.com
2013-12-27 10:06:58,209 ERROR: Object GET failed: https://region-a.geo-1.objects.hpcloudsvc.com:443/v1/94165097550687/bacongobbler/registry/repositories/library/ubuntu/_index_images 404 Not Found  [first 60 chars of response] <html><h1>Not Found</h1><p>The resource could not be found.<
Traceback (most recent call last):
  File "/home/bacongobbler/git/github.com/Stackato-Apps/docker-registry/venv/local/lib/python2.7/site-packages/swiftclient/client.py", line 1110, in _retry
    rv = func(self.url, self.token, *args, **kwargs)
  File "/home/bacongobbler/git/github.com/Stackato-Apps/docker-registry/venv/local/lib/python2.7/site-packages/swiftclient/client.py", line 758, in get_object
    http_response_content=body)
ClientException: Object GET failed: https://region-a.geo-1.objects.hpcloudsvc.com:443/v1/94165097550687/bacongobbler/registry/repositories/library/ubuntu/_index_images 404 Not Found  [first 60 chars of response] <html><h1>Not Found</h1><p>The resource could not be found.<
2013-12-27 10:06:58,305 INFO: 127.0.0.1 - - [27/Dec/2013 10:06:58] "PUT /v1/repositories/ubuntu/ HTTP/1.1" 200 -
2013-12-27 10:06:58,471 ERROR: Object GET failed: https://region-a.geo-1.objects.hpcloudsvc.com:443/v1/94165097550687/bacongobbler/registry/images/8dbd9e392a964056420e5d58ca5cc376ef18e2de93b5cc90e868a1bbc8318c1c/_inprogress 404 Not Found  [first 60 chars of response] <html><h1>Not Found</h1><p>The resource could not be found.<
Traceback (most recent call last):
  File "/home/bacongobbler/git/github.com/Stackato-Apps/docker-registry/venv/local/lib/python2.7/site-packages/swiftclient/client.py", line 1110, in _retry
    rv = func(self.url, self.token, *args, **kwargs)
  File "/home/bacongobbler/git/github.com/Stackato-Apps/docker-registry/venv/local/lib/python2.7/site-packages/swiftclient/client.py", line 758, in get_object
    http_response_content=body)
ClientException: Object GET failed: https://region-a.geo-1.objects.hpcloudsvc.com:443/v1/94165097550687/bacongobbler/registry/images/8dbd9e392a964056420e5d58ca5cc376ef18e2de93b5cc90e868a1bbc8318c1c/_inprogress 404 Not Found  [first 60 chars of response] <html><h1>Not Found</h1><p>The resource could not be found.<
2013-12-27 10:06:58,553 ERROR: Object GET failed: https://region-a.geo-1.objects.hpcloudsvc.com:443/v1/94165097550687/bacongobbler/registry/repositories/library/ubuntu/_private 404 Not Found  [first 60 chars of response] <html><h1>Not Found</h1><p>The resource could not be found.<
Traceback (most recent call last):
  File "/home/bacongobbler/git/github.com/Stackato-Apps/docker-registry/venv/local/lib/python2.7/site-packages/swiftclient/client.py", line 1110, in _retry
    rv = func(self.url, self.token, *args, **kwargs)
  File "/home/bacongobbler/git/github.com/Stackato-Apps/docker-registry/venv/local/lib/python2.7/site-packages/swiftclient/client.py", line 758, in get_object
    http_response_content=body)
ClientException: Object GET failed: https://region-a.geo-1.objects.hpcloudsvc.com:443/v1/94165097550687/bacongobbler/registry/repositories/library/ubuntu/_private 404 Not Found  [first 60 chars of response] <html><h1>Not Found</h1><p>The resource could not be found.<
2013-12-27 10:06:58,643 ERROR: Object GET failed: https://region-a.geo-1.objects.hpcloudsvc.com:443/v1/94165097550687/bacongobbler/registry/images/8dbd9e392a964056420e5d58ca5cc376ef18e2de93b5cc90e868a1bbc8318c1c/json 404 Not Found  [first 60 chars of response] <html><h1>Not Found</h1><p>The resource could not be found.<
Traceback (most recent call last):
  File "/home/bacongobbler/git/github.com/Stackato-Apps/docker-registry/venv/local/lib/python2.7/site-packages/swiftclient/client.py", line 1110, in _retry
    rv = func(self.url, self.token, *args, **kwargs)
  File "/home/bacongobbler/git/github.com/Stackato-Apps/docker-registry/venv/local/lib/python2.7/site-packages/swiftclient/client.py", line 758, in get_object
    http_response_content=body)
ClientException: Object GET failed: https://region-a.geo-1.objects.hpcloudsvc.com:443/v1/94165097550687/bacongobbler/registry/images/8dbd9e392a964056420e5d58ca5cc376ef18e2de93b5cc90e868a1bbc8318c1c/json 404 Not Found  [first 60 chars of response] <html><h1>Not Found</h1><p>The resource could not be found.<
2013-12-27 10:06:58,649 INFO: 127.0.0.1 - - [27/Dec/2013 10:06:58] "GET /v1/images/8dbd9e392a964056420e5d58ca5cc376ef18e2de93b5cc90e868a1bbc8318c1c/json HTTP/1.1" 404 -
2013-12-27 10:06:58,737 ERROR: Object DELETE failed: https://region-a.geo-1.objects.hpcloudsvc.com:443/v1/94165097550687/bacongobbler/registry/images/8dbd9e392a964056420e5d58ca5cc376ef18e2de93b5cc90e868a1bbc8318c1c/_checksum 404 Not Found  [first 60 chars of response] <html><h1>Not Found</h1><p>The resource could not be found.<
Traceback (most recent call last):
  File "/home/bacongobbler/git/github.com/Stackato-Apps/docker-registry/venv/local/lib/python2.7/site-packages/swiftclient/client.py", line 1110, in _retry
    rv = func(self.url, self.token, *args, **kwargs)
  File "/home/bacongobbler/git/github.com/Stackato-Apps/docker-registry/venv/local/lib/python2.7/site-packages/swiftclient/client.py", line 1017, in delete_object
    http_response_content=body)
ClientException: Object DELETE failed: https://region-a.geo-1.objects.hpcloudsvc.com:443/v1/94165097550687/bacongobbler/registry/images/8dbd9e392a964056420e5d58ca5cc376ef18e2de93b5cc90e868a1bbc8318c1c/_checksum 404 Not Found  [first 60 chars of response] <html><h1>Not Found</h1><p>The resource could not be found.<
2013-12-27 10:06:58,822 ERROR: Object GET failed: https://region-a.geo-1.objects.hpcloudsvc.com:443/v1/94165097550687/bacongobbler/registry/images/8dbd9e392a964056420e5d58ca5cc376ef18e2de93b5cc90e868a1bbc8318c1c/json 404 Not Found  [first 60 chars of response] <html><h1>Not Found</h1><p>The resource could not be found.<
Traceback (most recent call last):
  File "/home/bacongobbler/git/github.com/Stackato-Apps/docker-registry/venv/local/lib/python2.7/site-packages/swiftclient/client.py", line 1110, in _retry
    rv = func(self.url, self.token, *args, **kwargs)
  File "/home/bacongobbler/git/github.com/Stackato-Apps/docker-registry/venv/local/lib/python2.7/site-packages/swiftclient/client.py", line 758, in get_object
    http_response_content=body)
ClientException: Object GET failed: https://region-a.geo-1.objects.hpcloudsvc.com:443/v1/94165097550687/bacongobbler/registry/images/8dbd9e392a964056420e5d58ca5cc376ef18e2de93b5cc90e868a1bbc8318c1c/json 404 Not Found  [first 60 chars of response] <html><h1>Not Found</h1><p>The resource could not be found.<
2013-12-27 10:06:59,162 INFO: 127.0.0.1 - - [27/Dec/2013 10:06:59] "PUT /v1/images/8dbd9e392a964056420e5d58ca5cc376ef18e2de93b5cc90e868a1bbc8318c1c/json HTTP/1.1" 200 -
2013-12-27 10:06:59,985 ERROR: Object GET failed: https://region-a.geo-1.objects.hpcloudsvc.com:443/v1/94165097550687/bacongobbler/registry/images/8dbd9e392a964056420e5d58ca5cc376ef18e2de93b5cc90e868a1bbc8318c1c/layer 404 Not Found  [first 60 chars of response] <html><h1>Not Found</h1><p>The resource could not be found.<
Traceback (most recent call last):
  File "/home/bacongobbler/git/github.com/Stackato-Apps/docker-registry/venv/local/lib/python2.7/site-packages/swiftclient/client.py", line 1110, in _retry
    rv = func(self.url, self.token, *args, **kwargs)
  File "/home/bacongobbler/git/github.com/Stackato-Apps/docker-registry/venv/local/lib/python2.7/site-packages/swiftclient/client.py", line 758, in get_object
    http_response_content=body)
ClientException: Object GET failed: https://region-a.geo-1.objects.hpcloudsvc.com:443/v1/94165097550687/bacongobbler/registry/images/8dbd9e392a964056420e5d58ca5cc376ef18e2de93b5cc90e868a1bbc8318c1c/layer 404 Not Found  [first 60 chars of response] <html><h1>Not Found</h1><p>The resource could not be found.<
```

The `docker push` command eventually hangs at:

```
8dbd9e392a96: Pushing [=================================================> ]   134 MB/134.1 MB 0
```

It looks like some of the important files such as `layer` and `_checksum` are not pushed. Here is a tree of the container:

```
$ swift list bacongobbler | grep registry
registry/images/8dbd9e392a964056420e5d58ca5cc376ef18e2de93b5cc90e868a1bbc8318c1c/_inprogress
registry/images/8dbd9e392a964056420e5d58ca5cc376ef18e2de93b5cc90e868a1bbc8318c1c/ancestry
registry/images/8dbd9e392a964056420e5d58ca5cc376ef18e2de93b5cc90e868a1bbc8318c1c/json
registry/repositories/library/ubuntu/_index_images
```

My swift config in `config/config.yml`:

```
swift:
    storage: swift
    storage_path: /registry
    swift_authurl: https://region-a.geo-1.identity.hpcloudsvc.com:35357/v2.0
    swift_container: bacongobbler
    swift_user: ************
    swift_password: ****************
    swift_tenant_name: ************
    swift_region_name: region-a.geo-1
```

Any ideas why these files won't upload to swift?

**Comment by drobison00** [comment]
Could you elaborate on how you fixed this? I'm seeing the same issue, and so far as I can tell I'm not using anything wsgi related.

=== Registry side
29/Jan/2015:18:48:29 +0000 ERROR: Object HEAD failed: https://storage.us2.oraclecloud.com/v1/*******/docker-registry/registry/images/11a37ad47a09812819e6d5634ebcde508e9a49d186b9dc71bbc8885b1b4a2344/layer 404 Not Found
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/swiftclient/client.py", line 1208, in _retry
    rv = func(self.url, self.token, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/swiftclient/client.py", line 874, in head_object
    http_response_content=body)
ClientException: Object HEAD failed: https://storage.us2.oraclecloud.com/v1/*******/docker-registry/registry/images/11a37ad47a09812819e6d5634ebcde508e9a49d186b9dc71bbc8885b1b4a2344/layer 404 Not Found

=== Push side
d56e767abb61: Pushing [=================================================> ] 326.4 MB/326.8 MB 0

(just hangs here, forever)
