### ISSUE TITLE
Error when running with Gunicorn - "ImportError: No module named wsgi"

### ISSUE THREAD

**Issue by mccrodp** [docker/docker-registry#397]
I have tried to follow the instructions to clone the docker-registory so that I can save the docker images to a custom local directory in future. I have been able to set up and run the default docker registry before on an Ubuntu server. 

<code>docker run -p 5000:5000 registry</code>. 

However using gunicorn I am running into errors on a Debian Squeeze server with Apache running in worker mode. I have cloned the repository and run <code>pip install -r requirements.txt</code> successfully. I then try to run the registry application from the root directory of docker-registry.

<code>gunicorn --access-logfile - --debug -k gevent -b 0.0.0.0:5000 -w 1 docker_registry.wsgi:application</code>

I get the below error. Unfortunately I have no python experience, and searching the ImportError hasn't really helped me. Any pointers in the right direction are much appreciated. I have installed the <code>libapache2-mod-wsgi</code> package and ensured that wgsi is enabled at <code>/etc/apache2/mods-enabled/</code>. Thank you.

<pre>
2014-05-30 14:44:20 [10835] [INFO] Starting gunicorn 18.0
2014-05-30 14:44:21 [10835] [INFO] Listening at: http://0.0.0.0:5000 (10835)
2014-05-30 14:44:21 [10835] [INFO] Using worker: gevent
2014-05-30 14:44:21 [10840] [INFO] Booting worker with pid: 10840
2014-05-30 14:44:21 [10840] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/usr/local/lib/python2.6/dist-packages/gunicorn/arbiter.py", line 495, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.6/dist-packages/gunicorn/workers/base.py", line 106, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.6/dist-packages/gunicorn/app/base.py", line 114, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.6/dist-packages/gunicorn/app/wsgiapp.py", line 62, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python2.6/dist-packages/gunicorn/app/wsgiapp.py", line 49, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python2.6/dist-packages/gunicorn/util.py", line 354, in import_app
    __import__(module)
ImportError: No module named wsgi
Traceback (most recent call last):
  File "/usr/local/lib/python2.6/dist-packages/gunicorn/arbiter.py", line 495, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.6/dist-packages/gunicorn/workers/base.py", line 106, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.6/dist-packages/gunicorn/app/base.py", line 114, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.6/dist-packages/gunicorn/app/wsgiapp.py", line 62, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python2.6/dist-packages/gunicorn/app/wsgiapp.py", line 49, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python2.6/dist-packages/gunicorn/util.py", line 354, in import_app
    __import__(module)
ImportError: No module named wsgi
2014-05-30 14:44:21 [10840] [INFO] Worker exiting (pid: 10840)
2014-05-30 14:44:21 [10835] [INFO] Shutting down: Master
2014-05-30 14:44:21 [10835] [INFO] Reason: Worker failed to boot.
</pre>

**Comment by jeremyjjbrown** [comment]
@dmp42  Maybe your comments above could be in the README.

**Comment by dmp42** [comment]
@jeremyjjbrown the recommended way to run is documented here:

https://github.com/docker/docker-registry/#quick-start

Advanced use (direct binary launch, or using gunicorn) is documented in https://github.com/docker/docker-registry/blob/master/ADVANCED.md

(though these are provided more as a convenience)

Let me know if you feel anything is missing there (my comments are quite old here and the documentation moved a lot meanwhile).

Hope that helps.
