### ISSUE TITLE
Backend driver development environment How-to

### ISSUE THREAD

**Issue by pyotr777** [docker/docker-registry#602]
I have a few questions about development of new backend drivers. 

What would be the right development setup on Mac OS X? 
I understand that I can fork elliptics plugin (I did it already), change it, run tests with tox and, finally, upload to PyPI. Is that the right procedure? Did I miss anything?

How can I debug my driver? 
The only way I see is to download official docker registry image with `docker run registry`, get my code inside running registry container (via github with push and pull, for example. Unfortunately, mounting volumes doesn't work on boot2docker.), install with `python setup.py install` command, commit the container and create a new image, kill old container, run a new container from a new image. 
Is there a simpler way?

I also have problems running tox tests. When I run `tox` I get the following:

```
Traceback (most recent call last):
  File "/usr/local/bin/tox", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2603, in <module>
    working_set.require(__requires__)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 666, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 565, in resolve
    raise DistributionNotFound(req)  # XXX put more info here
pkg_resources.DistributionNotFound: virtualenv>=1.11.2
```

https://github.com/pyotr777/docker-registry/blob/master/CONTRIBUTING.md says that I might need to set $TOX_INCLUDE and $TOX_LIB environment variables. How exactly do I need to set them? 

Regards,
Peter

**Comment by pyotr777** [comment]
Greetings!
I have questions about python packages and importing. 

I have two directories: **docker-registry** -- clone of docker registry, and **docker-registry-driver-git** -- development directory for my backend driver. 

Before, in order to use docker registry with my driver,  I would run ```python setup.py develop``` in both directories, and docker registry would pick up the latest version of my driver from **docker-registry-driver-git/docker_registry/drivers/gitdriver.py**. 

Then I installed a new python version with brew and had to reinstall all packages. 

Now after I run 
```bash
~/work/docker/docker-registry > python setup.py develop
```
(in docker-registry directory), my driver can be used as:
```python
import docker_registry.drivers.gitdriver
```
And the source file used by registry for my driver is **docker-registry/docker_registry/drivers/gitdriver.py** -- not from my driver development directory (which is docker-registry-driver-git).

It seems to be correct behaviour of python importing system.

The question is, how can I make python to use source file from my development directory (**docker-registry-driver-git/docker_registry/drivers/gitdriver.py**)?

If I run 
```bash
~/work/docker/docker-registry-driver-git > python setup.py develop
...
Finished processing dependencies for gitdriver==0.7.103
```
The package seems to be installed, by I cannot import it:
```bash
~/work/docker/docker-registry-driver-git > pip list | grep gitdriver
gitdriver (0.7.103, /Users/peterbryzgalov/work/docker/docker-registry-driver-git)
~/work/docker/docker-registry-driver-git > python
Python 2.7.9 (default, Jan  3 2015, 14:21:36)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.54)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import gitdriver
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named gitdriver
>>>
```

**Comment by dmp42** [comment]
There should not exist any file like `docker-registry/docker_registry/drivers/gitdriver.py`

You should make a clean clone of docker-registry.

Also, for your driver structure, you may look at: https://github.com/noxiouz/docker-registry-driver-elliptics

(don't forget the __init__.py files with namespace initialization)

**Comment by pyotr777** [comment]
Thank you! 
I have removed ```docker-registry/docker_registry/drivers/gitdriver.py``` and could install my driver by running ```python setup.py develop``` in my driver top directory.

Now I want to test my driver. When I test my driver with nosetests, first I copy my driver directory inside a new folder inside docker registry directory, then I build a docker image with Dockerfile and copy docker registry folder into the image.
After container is started I install my driver from its folder inside docker registry directory with ```python setup.py install``` and run nosetests with ```python setup.py nosetests```. Copying driver directory into registry directory looks awkward to me, but I see no other way to get my driver inside docker image. 

What is the right procedure for testing a driver?

Regards,
Peter

**Comment by dmp42** [comment]
You don't need to do any of that.

Just run `python setup.py tests` from inside the docker-registry folder - it will test any installed driver (including yours).

**Comment by pyotr777** [comment]
I ran nosetests as you suggested. 
I get errors, but many of them seem to be irrelevant to my driver. In particular, I get lots of these:
```bash
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/nose/case.py", line 381, in setUp
    try_run(self.inst, ('setup', 'setUp'))
  File "/Library/Python/2.7/site-packages/nose/util.py", line 470, in try_run
    return func()
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/docker_registry/testing/driver.py", line 40, in setUp
    storage = driver.fetch(self.scheme)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/docker_registry/core/driver.py", line 269, in fetch
    module.Storage.scheme = name
AttributeError: 'module' object has no attribute 'Storage'
```

My driver was used during the tests: I can see its output and some errors referenced to my source file. 

On the last lines of the output I see coverage summary for docker registry modules(?) , but my driver is not there. 

How can I tell that my driver is OK and can be distributed?

**Comment by dmp42** [comment]
It seems you are back onto using (partly?) the system python instead of the brew one? (nose from system site-packages)

Either way, these errors do indicate a problem in your driver...

**Comment by pyotr777** [comment]
After reinstalling nose I still have similar errors:
```bash
======================================================================
ERROR: tests.test_all_installed_drivers.TestDrivertestjson.test_empty_after_remove_list_directory
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/nose/case.py", line 381, in setUp
    try_run(self.inst, ('setup', 'setUp'))
  File "/usr/local/lib/python2.7/site-packages/nose/util.py", line 470, in try_run
    return func()
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/docker_registry/testing/driver.py", line 40, in setUp
    storage = driver.fetch(self.scheme)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/docker_registry/core/driver.py", line 269, in fetch
    module.Storage.scheme = name
AttributeError: 'module' object has no attribute 'Storage'
-------------------- >> begin captured stdout << ---------------------
Read JSON from /Users/peterbryzgalov/gitstorage/git_storage/images/511136ea3c5a64f264b78b5433614aec563103b4d4702f3ba7d4d2698e22c158/json
container_config=
{u'AttachStderr': False,
 u'AttachStdin': False,
 u'AttachStdout': False,
 u'Cmd': None,
 u'CpuShares': 0,
 u'Dns': None,
 u'Env': None,
 u'Hostname': u'',
 u'Image': u'',
 u'Memory': 0,
 u'MemorySwap': 0,
 u'OpenStdin': False,
 u'PortSpecs': None,
 u'StdinOnce': False,
 u'Tty': False,
 u'User': u'',
 u'Volumes': None,
 u'VolumesFrom': u''}
CMD=None

--------------------- >> end captured stdout << ----------------------
-------------------- >> begin captured logging << --------------------
docker_registry.core.driver: DEBUG: Will return docker-registry.drivers.testjson.Storage
--------------------- >> end captured logging << ---------------------

```

**Comment by pyotr777** [comment]
Greetings!
Now there is only one failure when I run nosetests:
```
FAIL: test_nginx_accel_redirect_layer (tests.test_images.TestImages)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/peterbryzgalov/work/docker/docker-registry/tests/test_images.py", line 30, in test_nginx_accel_redirect_layer
    'Store must be LocalStorage')
AssertionError: Store must be LocalStorage
```
In the test code we have:
```
self.assertTrue(images.store.scheme == 'file',
                        'Store must be LocalStorage')
```
So this tests if the storage scheme name is "file". My scheme name is different: "gitdriver".

I still have questions about testing and distributing my driver.

I run nosetests in docker-registry folder.
In my driver folder I run flake8. I formatted my code, so now it gives no errors or warnings.

https://github.com/docker/docker-registry/blob/master/CONTRIBUTING.md suggests that I also run tox. 
When I run tox in docker-registry folder I get the following error and summary:
```bash
ERROR: InvocationError: '/Users/peterbryzgalov/work/docker/docker-registry/.tox/flake8/bin/flake8 /Users/peterbryzgalov/work/docker/docker-registry'
...
Ran 128 tests in 5.328s

OK
_____ summary ____
ERROR:   flake8: commands failed
  py26: commands succeeded
  py27: commands succeeded
```

File .tox/flake8/bin/flake8 exists. 

* Do I have to do anything about tox-flake8 error?

* When I finished tests, how do I distribute my driver?

I submitted my package to pypi.python.org and it got registered.
But even if it is possible to install it with pip install, how are users supposed to use it?
Docker registry is run within a container from Docker hub, so I guess it is necessary to include my driver into this image, so that users can do:
```bash
docker run -e SETTINGS_FLAVOR=gitdriver -p 5000:5000 registry
```
* Is it possible to include gitdriver into registry image?

Regards,
Peter
