### ISSUE TITLE
Couldn't push Docker Image when use with Swift as storage

### ISSUE THREAD

**Issue by winggundamth** [docker/docker-registry#724]
I install and config docker-registry with this command and it's working fine. I can start docker-registry

```
root@docker-registry:/# pip install docker-registry docker-registry-driver-swift
root@docker-registry:/# docker-registry
2014-11-13 17:46:26 [89] [INFO] Starting gunicorn 19.1.0
2014-11-13 17:46:26 [89] [INFO] Listening at: http://0.0.0.0:5000 (89)
2014-11-13 17:46:26 [89] [INFO] Using worker: gevent
2014-11-13 17:46:26 [98] [INFO] Booting worker with pid: 98
2014-11-13 17:46:26 [99] [INFO] Booting worker with pid: 99
2014-11-13 17:46:26 [102] [INFO] Booting worker with pid: 102
2014-11-13 17:46:26 [105] [INFO] Booting worker with pid: 105
2014-11-13 17:46:26 [89] [INFO] 4 workers
13/Nov/2014:17:46:26 +0000 INFO: Enabling storage cache on Redis
13/Nov/2014:17:46:26 +0000 INFO: Redis host: 127.0.0.1:6379 (db0)
13/Nov/2014:17:46:26 +0000 INFO: Enabling lru cache on Redis
13/Nov/2014:17:46:26 +0000 INFO: Redis lru host: 127.0.0.1:6379 (db0)
13/Nov/2014:17:46:26 +0000 INFO: Enabling storage cache on Redis
13/Nov/2014:17:46:26 +0000 INFO: Redis config: {'path': '/registry', 'host': '127.0.0.1', 'password': None, 'db': 0, 'port': 6379}
13/Nov/2014:17:46:26 +0000 DEBUG: Will return docker-registry.drivers.swift.Storage
13/Nov/2014:17:46:26 +0000 INFO: Enabling storage cache on Redis
13/Nov/2014:17:46:26 +0000 INFO: Redis host: 127.0.0.1:6379 (db0)
13/Nov/2014:17:46:26 +0000 INFO: Enabling lru cache on Redis
13/Nov/2014:17:46:26 +0000 INFO: Redis lru host: 127.0.0.1:6379 (db0)
13/Nov/2014:17:46:26 +0000 INFO: Enabling storage cache on Redis
13/Nov/2014:17:46:26 +0000 INFO: Redis config: {'path': '/registry', 'host': '127.0.0.1', 'password': None, 'db': 0, 'port': 6379}
13/Nov/2014:17:46:26 +0000 DEBUG: Will return docker-registry.drivers.swift.Storage
13/Nov/2014:17:46:27 +0000 INFO: Enabling storage cache on Redis
13/Nov/2014:17:46:27 +0000 INFO: Redis host: 127.0.0.1:6379 (db0)
13/Nov/2014:17:46:27 +0000 INFO: Enabling lru cache on Redis
13/Nov/2014:17:46:27 +0000 INFO: Redis lru host: 127.0.0.1:6379 (db0)
13/Nov/2014:17:46:27 +0000 INFO: Enabling storage cache on Redis
13/Nov/2014:17:46:27 +0000 INFO: Redis config: {'path': '/registry', 'host': '127.0.0.1', 'password': None, 'db': 0, 'port': 6379}
13/Nov/2014:17:46:27 +0000 DEBUG: Will return docker-registry.drivers.swift.Storage
13/Nov/2014:17:46:27 +0000 INFO: Enabling storage cache on Redis
13/Nov/2014:17:46:27 +0000 INFO: Redis host: 127.0.0.1:6379 (db0)
13/Nov/2014:17:46:27 +0000 INFO: Enabling lru cache on Redis
13/Nov/2014:17:46:27 +0000 INFO: Redis lru host: 127.0.0.1:6379 (db0)
13/Nov/2014:17:46:27 +0000 INFO: Enabling storage cache on Redis
13/Nov/2014:17:46:27 +0000 INFO: Redis config: {'path': '/registry', 'host': '127.0.0.1', 'password': None, 'db': 0, 'port': 6379}
13/Nov/2014:17:46:27 +0000 DEBUG: Will return docker-registry.drivers.swift.Storage
```

This is my configuration

```
root@docker-registry:/# pip list
argparse (1.2.1)
Babel (1.3)
backports.lzma (0.0.3)
blinker (1.3)
boto (2.34.0)
chardet (2.2.1)
docker-registry (0.9.0)
docker-registry-core (2.0.3)
docker-registry-driver-swift (0.2.1)
Flask (0.10.1)
gevent (1.0.1)
greenlet (0.4.5)
gunicorn (19.1.0)
iso8601 (0.1.10)
itsdangerous (0.24)
Jinja2 (2.7.3)
lxml (3.4.0)
MarkupSafe (0.23)
netaddr (0.7.12)
oslo.config (1.4.0)
pbr (0.10.0)
pip (1.5.6)
prettytable (0.7.2)
pyasn1 (0.1.7)
python-keystoneclient (0.10.0)
python-swiftclient (2.2.0)
pytz (2014.9)
PyYAML (3.11)
redis (2.10.3)
requests (2.3.0)
rsa (3.1.4)
setuptools (5.8)
simplejson (3.6.2)
six (1.7.3)
SQLAlchemy (0.9.4)
ssh-import-id (3.21)
stevedore (1.1.0)
urllib3 (1.8.3)
Werkzeug (0.9.6)
wsgiref (0.1.2)
```

```
export SEARCH_BACKEND=sqlalchemy
export SQLALCHEMY_INDEX_DATABASE=sqlite:////docker-registry/docker-registry.db
export CACHE_REDIS_HOST=127.0.0.1
export CACHE_REDIS_PORT=6379
export CACHE_LRU_REDIS_HOST=127.0.0.1
export CACHE_LRU_REDIS_PORT=6379
export DEBUG=true
export LOGLEVEL=debug
export DOCKER_REGISTRY_CONFIG=/docker-registry/config.yml
export SETTINGS_FLAVOR=swift
export STORAGE_PATH=/registry
export OS_AUTH_URL=https://identity.example.com/v2.0
export OS_CONTAINER=registry
export OS_USERNAME=keystoneuser
export OS_PASSWORD=keystonepass
export OS_TENANT_NAME=swift-registry
```

But after I tried to push Docker Image to it I got an error below

```
172.17.42.1 - - [13/Nov/2014:17:46:52 +0000] "GET /v1/users/ HTTP/1.0" 200 4 "-" "docker/1.3.1 go/go1.3.3 git-commit/4e9bbfa kernel/3.16.0-25-generic os/linux arch/amd64"
13/Nov/2014:17:46:58 +0000 DEBUG: args = {'namespace': 'library', 'repository': u'ubuntu'}
13/Nov/2014:17:46:58 +0000 DEBUG: REQ: curl -i -X POST https://identity.example.com/v2.0/tokens -H "Content-Type: application/json" -H "Accept: application/json" -H "User-Agent: python-keystoneclient" -d '{"auth": {"tenantName": "swift-registry", "pas
swordCredentials": {"username": "keystoneuser", "password": "keystonepass"}}}'
13/Nov/2014:17:46:58 +0000 INFO: Starting new HTTPS connection (1): identity.example.com
13/Nov/2014:17:46:58 +0000 ERROR: Authorization Failure. Authorization Failed: __init__() got an unexpected keyword argument 'server_hostname'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/swiftclient/client.py", line 1200, in _retry
    self.url, self.token = self.get_auth()
  File "/usr/local/lib/python2.7/dist-packages/swiftclient/client.py", line 1174, in get_auth
    insecure=self.insecure)
  File "/usr/local/lib/python2.7/dist-packages/swiftclient/client.py", line 371, in get_auth
    insecure=insecure)
  File "/usr/local/lib/python2.7/dist-packages/swiftclient/client.py", line 308, in get_keystoneclient_2_0
    raise ClientException('Authorization Failure. %s' % err)
ClientException: Authorization Failure. Authorization Failed: __init__() got an unexpected keyword argument 'server_hostname'
13/Nov/2014:17:46:58 +0000 DEBUG: REQ: curl -i -X POST https://identity.example.com/v2.0/tokens -H "Content-Type: application/json" -H "Accept: application/json" -H "User-Agent: python-keystoneclient" -d '{"auth": {"tenantName": "swift-registry", "pas
swordCredentials": {"username": "keystoneuser", "password": "keystoneuser"}}}'
13/Nov/2014:17:46:58 +0000 INFO: Starting new HTTPS connection (1): identity.example.com
13/Nov/2014:17:46:58 +0000 ERROR: Authorization Failure. Authorization Failed: __init__() got an unexpected keyword argument 'server_hostname'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/swiftclient/client.py", line 1200, in _retry
    self.url, self.token = self.get_auth()
  File "/usr/local/lib/python2.7/dist-packages/swiftclient/client.py", line 1174, in get_auth
    insecure=self.insecure)
  File "/usr/local/lib/python2.7/dist-packages/swiftclient/client.py", line 371, in get_auth
    insecure=insecure)
  File "/usr/local/lib/python2.7/dist-packages/swiftclient/client.py", line 308, in get_keystoneclient_2_0
    raise ClientException('Authorization Failure. %s' % err)
ClientException: Authorization Failure. Authorization Failed: __init__() got an unexpected keyword argument 'server_hostname'
2014-11-13 17:46:58,772 ERROR: Exception on /v1/repositories/ubuntu/ [PUT]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/toolkit.py", line 277, in wrapper
    return f(namespace=namespace, repository=repository, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/toolkit.py", line 251, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/index.py", line 98, in put_repository
    update_index_images(namespace, repository, flask.request.data)
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/index.py", line 80, in update_index_images
    store.put_content(path, data_arg)
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/core/lru.py", line 78, in wrapper
    return f(*args)
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/drivers/swift.py", line 75, in put_content
    self.put_store(path, content)
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/drivers/swift.py", line 85, in put_store
    raise IOError("Could not put content: %s" % path)
IOError: Could not put content: registry/repositories/library/ubuntu/_index_images
13/Nov/2014:17:46:58 +0000 ERROR: Exception on /v1/repositories/ubuntu/ [PUT]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/toolkit.py", line 277, in wrapper
    return f(namespace=namespace, repository=repository, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/toolkit.py", line 251, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/index.py", line 98, in put_repository
    update_index_images(namespace, repository, flask.request.data)
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/index.py", line 80, in update_index_images
    store.put_content(path, data_arg)
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/core/lru.py", line 78, in wrapper
    return f(*args)
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/drivers/swift.py", line 75, in put_content
    self.put_store(path, content)
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/drivers/swift.py", line 85, in put_store
    raise IOError("Could not put content: %s" % path)
IOError: Could not put content: registry/repositories/library/ubuntu/_index_images
172.17.42.1 - - [13/Nov/2014:17:46:58 +0000] "PUT /v1/repositories/ubuntu/ HTTP/1.0" 500 291 "-" "docker/1.3.1 go/go1.3.3 git-commit/4e9bbfa kernel/3.16.0-25-generic os/linux arch/amd64"
```

I don't know how to fix this. Have anyone success on using Swift as storage before?

**Comment by sunil3s3** [comment]
hi ,

Im facing same issue with swift storage as  yours. any solution for this?
