### ISSUE TITLE
Unable to run docker registry in first attempt

### ISSUE THREAD

**Issue by koyadume** [docker/docker-registry#796]
I am running ubuntu server 14.10 inside virtualbox on my windows 7 box. I tried to run docker registry using `docker run -p 5000:5000 registry` command but it failed with following error -

shailendra@shailendra-ubuntu:~$ sudo docker run -p 5000:5000 registry
Unable to find image 'registry' locally
registry:latest: The image you are pulling has been verified
21e2a9181f28: Pull complete
d3c7d7bb7b97: Pull complete
b428b41004f7: Pull complete
882b5f73341c: Pull complete
2656b141f0de: Pull complete
d163725a45a5: Pull complete
140182e77bf9: Pull complete
fc7d2ef9314e: Pull complete
60236035d63e: Pull complete
82518c42ab88: Pull complete
511136ea3c5a: Already exists
5bc37dc2dfba: Already exists
61cb619d86bc: Already exists
3f45ca85fedc: Already exists
78e82ee876a2: Already exists
dc07507cef42: Already exists
86ce37374f40: Already exists
Status: Downloaded newer image for registry:latest
2014-11-26 23:32:57 [1] [INFO] Starting gunicorn 19.1.0
2014-11-26 23:32:57 [1] [INFO] Listening at: http://0.0.0.0:5000 (1)
2014-11-26 23:32:57 [1] [INFO] Using worker: gevent
2014-11-26 23:32:57 [17] [INFO] Booting worker with pid: 17
2014-11-26 23:32:57 [18] [INFO] Booting worker with pid: 18
2014-11-26 23:32:57 [19] [INFO] Booting worker with pid: 19
2014-11-26 23:32:57 [20] [INFO] Booting worker with pid: 20
2014-11-26 23:32:57 [1] [INFO] 4 workers
26/Nov/2014:23:32:57 +0000 WARNING: Cache storage disabled!
26/Nov/2014:23:32:57 +0000 WARNING: LRU cache disabled!
26/Nov/2014:23:32:57 +0000 WARNING: Cache storage disabled!
26/Nov/2014:23:32:57 +0000 WARNING: LRU cache disabled!
26/Nov/2014:23:32:57 +0000 DEBUG: Will return docker-registry.drivers.file.Storage
26/Nov/2014:23:32:57 +0000 DEBUG: Will return docker-registry.drivers.file.Storage
26/Nov/2014:23:32:58 +0000 WARNING: Cache storage disabled!
26/Nov/2014:23:32:58 +0000 WARNING: LRU cache disabled!
26/Nov/2014:23:32:58 +0000 DEBUG: Will return docker-registry.drivers.file.Storage
26/Nov/2014:23:32:58 +0000 WARNING: Cache storage disabled!
26/Nov/2014:23:32:58 +0000 WARNING: LRU cache disabled!
26/Nov/2014:23:32:58 +0000 DEBUG: Will return docker-registry.drivers.file.Storage
2014-11-26 23:32:58 [18] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/ggevent.py", line 193, in init_process
    super(GeventWorker, self).init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 114, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 356, in import_app
    **import**(module)
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/wsgi.py", line 27, in <module>
    from .search import \*  # noqa
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/search.py", line 14, in <module>
    INDEX = index.load(cfg.search_backend.lower())
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/lib/index/**init**.py", line 82, in load
    return db.SQLAlchemyIndex()
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/lib/index/db.py", line 61, in **init**
    self._setup_database()
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/lib/index/db.py", line 76, in _setup_database
    self._generate_index(session=session)
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/lib/index/db.py", line 85, in _generate_index
    session.commit()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 765, in commit
    self.transaction.commit()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 370, in commit
    self._prepare_impl()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 350, in _prepare_impl
    self.session.flush()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 1903, in flush
    self._flush(objects)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 2021, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/langhelpers.py", line 57, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 1985, in _flush
    flush_context.execute()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/unitofwork.py", line 370, in execute
    rec.execute(self)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/unitofwork.py", line 523, in execute
    uow
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/persistence.py", line 64, in save_obj
    mapper, table, insert)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/persistence.py", line 562, in _emit_insert_statements
    execute(statement, multiparams)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 720, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/elements.py", line 317, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 817, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 947, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1108, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 185, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 940, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 435, in do_execute
    cursor.execute(statement, parameters)
IntegrityError: (IntegrityError) UNIQUE constraint failed: version.id u'INSERT INTO version (id) VALUES (?)' (1,)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/ggevent.py", line 193, in init_process
    super(GeventWorker, self).init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 114, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 356, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/wsgi.py", line 27, in <module>
    from .search import \*  # noqa
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/search.py", line 14, in <module>
    INDEX = index.load(cfg.search_backend.lower())
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/lib/index/**init**.py", line 82, in load
    return db.SQLAlchemyIndex()
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/lib/index/db.py", line 61, in **init**
    self._setup_database()
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/lib/index/db.py", line 76, in _setup_database
    self._generate_index(session=session)
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/lib/index/db.py", line 85, in _generate_index
    session.commit()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 765, in commit
    self.transaction.commit()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 370, in commit
    self._prepare_impl()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 350, in _prepare_impl
    self.session.flush()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 1903, in flush
    self._flush(objects)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 2021, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/langhelpers.py", line 57, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 1985, in _flush
    flush_context.execute()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/unitofwork.py", line 370, in execute
    rec.execute(self)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/unitofwork.py", line 523, in execute
    uow
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/persistence.py", line 64, in save_obj
    mapper, table, insert)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/persistence.py", line 562, in _emit_insert_statements
    execute(statement, multiparams)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 720, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/elements.py", line 317, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 817, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 947, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1108, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 185, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 940, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 435, in do_execute
    cursor.execute(statement, parameters)
IntegrityError: (IntegrityError) UNIQUE constraint failed: version.id u'INSERT INTO version (id) VALUES (?)' (1,)
2014-11-26 23:32:58 [18] [INFO] Worker exiting (pid: 18)
2014-11-26 23:32:59 [17] [INFO] Worker exiting (pid: 17)
2014-11-26 23:32:59 [19] [INFO] Worker exiting (pid: 19)
2014-11-26 23:32:59 [20] [INFO] Worker exiting (pid: 20)
2014-11-26 23:32:59 [1] [INFO] Shutting down: Master
2014-11-26 23:32:59 [1] [INFO] Reason: Worker failed to boot.

However it worked after i executed same command again -
shailendra@shailendra-ubuntu:~$ sudo docker run -p 5000:5000 registry
[sudo] password for shailendra:
2014-11-26 23:50:16 [1] [INFO] Starting gunicorn 19.1.0
2014-11-26 23:50:16 [1] [INFO] Listening at: http://0.0.0.0:5000 (1)
2014-11-26 23:50:16 [1] [INFO] Using worker: gevent
2014-11-26 23:50:16 [13] [INFO] Booting worker with pid: 13
2014-11-26 23:50:16 [14] [INFO] Booting worker with pid: 14
2014-11-26 23:50:16 [15] [INFO] Booting worker with pid: 15
2014-11-26 23:50:16 [16] [INFO] Booting worker with pid: 16
2014-11-26 23:50:16 [1] [INFO] 4 workers
26/Nov/2014:23:50:17 +0000 WARNING: Cache storage disabled!
26/Nov/2014:23:50:17 +0000 WARNING: LRU cache disabled!
26/Nov/2014:23:50:17 +0000 DEBUG: Will return docker-registry.drivers.file.Storage
26/Nov/2014:23:50:17 +0000 WARNING: Cache storage disabled!
26/Nov/2014:23:50:17 +0000 WARNING: LRU cache disabled!
26/Nov/2014:23:50:17 +0000 DEBUG: Will return docker-registry.drivers.file.Storage
26/Nov/2014:23:50:17 +0000 WARNING: Cache storage disabled!
26/Nov/2014:23:50:17 +0000 WARNING: Cache storage disabled!
26/Nov/2014:23:50:17 +0000 WARNING: LRU cache disabled!
26/Nov/2014:23:50:17 +0000 WARNING: LRU cache disabled!
26/Nov/2014:23:50:17 +0000 DEBUG: Will return docker-registry.drivers.file.Storage
26/Nov/2014:23:50:17 +0000 DEBUG: Will return docker-registry.drivers.file.Storage
# 

shailendra@shailendra-ubuntu:~$ curl http://localhost:5555/version | python -mjson.tool
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   148  100   148    0     0   7842      0 --:--:-- --:--:-- --:--:--  8222
{
    "ApiVersion": "1.15",
    "Arch": "amd64",
    "GitCommit": "4e9bbfa",
    "GoVersion": "go1.3.3",
    "KernelVersion": "3.16.0-23-generic",
    "Os": "linux",
    "Version": "1.3.1"
}

**Comment by remoe** [comment]
Thanks @sgirones. This fixes also this issue on my system (docker-1.4.1, coreos 575.0)
