### ISSUE TITLE
500 on /v1/_ping

### ISSUE THREAD

**Issue by bjaglin** [docker/docker-registry#802]
After upgrading our containerized private registry to 0.9 via via `docker run -d --name docker-registry -v /var/lib/docker/registry:/tmp/registry -p 5000:5000 -e CORS_ORIGINS=[\'*\'] registry:0.9.0`, `/v1/_ping` (which used to return 200/"true" on <0.9) is returning a 500.

```
2014-11-29 12:49:42,303 ERROR: Exception on /v1/_ping [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/app.py", line 44, in ping
    version = module.__version__
  File "/usr/lib/python2.7/dist-packages/six.py", line 116, in __getattr__
    _module = self._resolve()
  File "/usr/lib/python2.7/dist-packages/six.py", line 105, in _resolve
    return _import_module(self.mod)
  File "/usr/lib/python2.7/dist-packages/six.py", line 76, in _import_module
    __import__(name)
  File "/usr/lib/python2.7/lib-tk/tkCommonDialog.py", line 11, in <module>
    from Tkinter import *
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 42, in <module>
    raise ImportError, str(msg) + ', please install the python-tk package'
ImportError: No module named _tkinter, please install the python-tk package
```

After `docker exec docker-registry sh -c 'apt-get update && apt-get install python-tk'`, I am getting another error:
```
9/Nov/2014:12:51:40 +0000 ERROR: Exception on /v1/_ping [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/app.py", line 44, in ping
    version = module.__version__
  File "/usr/lib/python2.7/dist-packages/six.py", line 116, in __getattr__
    _module = self._resolve()
  File "/usr/lib/python2.7/dist-packages/six.py", line 105, in _resolve
    return _import_module(self.mod)
  File "/usr/lib/python2.7/dist-packages/six.py", line 76, in _import_module
    __import__(name)
ImportError: No module named _winreg
```

A bit of googling seem to show that `_winreg` was renamed to `winreg` in Python 3, but:
```
bjaglin@caro:~$ docker exec -ti docker-registry python --version
Python 2.7.6
```

I reached the limits of my (inexistent) Python knowledge... Any workaround until 0.9.1 is cut out?

~~FWIW, our registry is behind an nginx doing HTTPS termination and basic_auth.~~ The 500 is also thrown without proxying through nginx.

**Comment by xiaods** [comment]
0.9.1 also not fix it.

**Comment by dmp42** [comment]
@xiaods don't run with debug true.

**Comment by xiaods** [comment]
@dmp42 OK

**Comment by dmp42** [comment]
@xiaods add `-e DEBUG=false` or use a flavor that doesn't set debug.

Hope that helps!

**Comment by xiaods** [comment]
@dmp42 yes, it works. but i need below function:
curl https://my.docker.registry.com/v1/_ping
true

currently it now return a {}

**Comment by dmp42** [comment]
Yes, _ping (now) returns a json object.

**Comment by xiaods** [comment]
@dmp42 so {} is correct? can we return some status code?

**Comment by dmp42** [comment]
Status code is 200.

**Comment by xiaods** [comment]
@dmp42 got it.
