### ISSUE TITLE
Error when writing the checksum on private registry

### ISSUE THREAD

**Issue by rchaudha** [docker/docker-registry#824]
Hi,

I just saw the following error when the checksum was being written by the registry:

```
ERROR: Exception on /v1/images/cbd7a6c6412ecdbcb4daef4a42195d0a93fc774ff306b6fb7fd65a69147bcdc4/checksum [PUT]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/toolkit.py", line 250, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/images.py", line 285, in put_image_checksum
    checksums = load_checksums(image_id)
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/images.py", line 373, in load_checksums
    data = store.get_content(checksum_path)
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/drivers/file.py", line 55, in get_content
    raise exceptions.FileNotFoundError('%s is not there' % path)
FileNotFoundError: /var/lib/docker-registry/images/cbd7a6c6412ecdbcb4daef4a42195d0a93fc774ff306b6fb7fd65a69147bcdc4/_checksum is not there
```

Any hints?  Retry on docker push actually works fine.

Thanks,
Rohit

**Comment by BugRoger** [comment]
As reference this is a duplicate of #775. The same fix applies.
