### ISSUE TITLE
http 500 error while deleting tags or repositories

### ISSUE THREAD

**Issue by JeffChien** [docker/docker-registry#903]
Hi, I'm encountering http 500 internal error with these two API
http://docs.docker.com/reference/api/registry_api/#delete-a-repository-tag
http://docs.docker.com/reference/api/registry_api/#delete-a-repository

it only happen when I enable redis cache, the following is my config and call stack log

```
SETTINGS_FLAVOR=local
STORAGE_PATH=/registry
SEARCH_BACKEND=sqlalchemy
STANDALONE=true
```

```
Traceback (most recent call last):                               
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()                      
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)                           
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)                             
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()                                 
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/toolkit.py", line 306, in wrapper
    return f(namespace=namespace, repository=repository, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/toolkit.py", line 280, in wrapper
    return f(*args, **kwargs)                                    
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/tags.py", line 262, in delete_repository
    namespace=namespace, repository=repository, tag=tag_name) 
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/tags.py", line 214, in delete_tag                                        
    image = store.get_content(path=tag_path)                     
TypeError: wrapper() got an unexpected keyword argument 'path'
```

**Comment by dmp42** [comment]
Thanks. I'll look into it.

**Comment by deimosfr** [comment]
+1
