### ISSUE TITLE
registry can not be startup

### ISSUE THREAD

**Issue by epiphyllum** [docker/docker-registry#922]
root@docker:/home/zft# docker run -p 5000:5000 registry
Unable to find image 'registry' locally
Pulling repository registry

c55308716b36: Download complete 
511136ea3c5a: Download complete 
27d47432a69b: Download complete 
5f92234dcf1e: Download complete 
51a9c7c1f8bb: Download complete 
5ba9dab47459: Download complete 
30e25c7b70df: Download complete 
ed34dec80489: Download complete 
0e7a483810f6: Download complete 
eaebc036889a: Download complete 
8ec695ba9240: Download complete 
ecc59b06f5b7: Download complete 
63ad05f3af00: Download complete 
f054bc98768f: Download complete 
214c09aed08b: Download complete 
[2015-02-03 07:11:02 +0000] [1] [INFO] Starting gunicorn 19.1.1
[2015-02-03 07:11:02 +0000] [1] [INFO] Listening at: http://0.0.0.0:5000 (1)
[2015-02-03 07:11:02 +0000] [1] [INFO] Using worker: gevent
[2015-02-03 07:11:02 +0000] [13] [INFO] Booting worker with pid: 13
[2015-02-03 07:11:02 +0000] [14] [INFO] Booting worker with pid: 14
[2015-02-03 07:11:02 +0000] [15] [INFO] Booting worker with pid: 15
[2015-02-03 07:11:02 +0000] [16] [INFO] Booting worker with pid: 16
03/Feb/2015:07:11:03 +0000 WARNING: Cache storage disabled!
03/Feb/2015:07:11:03 +0000 WARNING: LRU cache disabled!
03/Feb/2015:07:11:03 +0000 WARNING: Cache storage disabled!
03/Feb/2015:07:11:03 +0000 WARNING: LRU cache disabled!
03/Feb/2015:07:11:03 +0000 DEBUG: Will return docker-registry.drivers.file.Storage
03/Feb/2015:07:11:03 +0000 DEBUG: Will return docker-registry.drivers.file.Storage
03/Feb/2015:07:11:03 +0000 WARNING: Cache storage disabled!
03/Feb/2015:07:11:03 +0000 WARNING: LRU cache disabled!
03/Feb/2015:07:11:03 +0000 DEBUG: Will return docker-registry.drivers.file.Storage
03/Feb/2015:07:11:03 +0000 WARNING: Cache storage disabled!
03/Feb/2015:07:11:03 +0000 WARNING: LRU cache disabled!
03/Feb/2015:07:11:03 +0000 DEBUG: Will return docker-registry.drivers.file.Storage
03/Feb/2015:07:11:03 +0000 WARNING: Another process is creating the search database
03/Feb/2015:07:11:03 +0000 WARNING: DB is disconnected. Reconnect to it.
[2015-02-03 07:11:03 +0000] [13] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/ggevent.py", line 193, in init_process
    super(GeventWorker, self).init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 114, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 356, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/wsgi.py", line 27, in <module>
    from .search import *  # noqa
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/search.py", line 14, in <module>
    INDEX = index.load(cfg.search_backend.lower())
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/lib/index/__init__.py", line 82, in load
    return db.SQLAlchemyIndex()
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/lib/index/db.py", line 86, in __init__
    self._setup_database()
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/toolkit.py", line 330, in wrapper
    os.remove(lock_path)
OSError: [Errno 2] No such file or directory: './registry._setup_database.lock'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/ggevent.py", line 193, in init_process
    super(GeventWorker, self).init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 114, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 356, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/wsgi.py", line 27, in <module>
    from .search import *  # noqa
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/search.py", line 14, in <module>
    INDEX = index.load(cfg.search_backend.lower())
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/lib/index/__init__.py", line 82, in load
    return db.SQLAlchemyIndex()
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/lib/index/db.py", line 86, in __init__
    self._setup_database()
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/toolkit.py", line 330, in wrapper
    os.remove(lock_path)
OSError: [Errno 2] No such file or directory: './registry._setup_database.lock'
[2015-02-03 07:11:03 +0000] [13] [INFO] Worker exiting (pid: 13)
[2015-02-03 07:11:04 +0000] [15] [INFO] Worker exiting (pid: 15)
[2015-02-03 07:11:04 +0000] [14] [INFO] Worker exiting (pid: 14)
[2015-02-03 07:11:04 +0000] [16] [INFO] Worker exiting (pid: 16)
[2015-02-03 07:11:04 +0000] [1] [INFO] Shutting down: Master
[2015-02-03 07:11:04 +0000] [1] [INFO] Reason: Worker failed to boot.
root@docker:/home/zft#

**Comment by Caligone** [comment]
Same issue here with `Docker version 1.4.1, build 5bc2ff8` on an Archlinux

**Comment by dmp42** [comment]
`GUNICORN_OPTS=[--preload]` should help you out (or disable the search).
It's a duplicate - will be fixed soon.
