### ISSUE TITLE
Exception while using s3

### ISSUE THREAD

**Issue by aviz** [docker/docker-registry#972]
I am getting the following while using S3 as the storage.
When i move to local, everything works fine.
I am using the following command to start the registry docker
docker run \
         -e SETTINGS_FLAVOR=s3 \
         -e AWS_BUCKET=dockers-images \
         -e STORAGE_PATH=/registry \
         -e AWS_ENCRYPT=false \
         -e AWS_SECURE=false \
         -e AWS_REGION=us-east-1 \
         -e AWS_KEY=SOMETHINGSOMETHING \
         -e AWS_SECRET=SOMETHINGSECRET\
         -e SEARCH_BACKEND=sqlalchemy \
         -p 5000:5000 \
         registry

Any ideas ?

172.17.42.1 - - [22/Mar/2015:18:13:43 +0000] "GET /v1/_ping HTTP/1.1" 200 2 "-" "Go 1.1 package http"
172.17.42.1 - - [22/Mar/2015:18:13:43 +0000] "GET /v2/ HTTP/1.1" 404 233 "-" "Go 1.1 package http"
172.17.42.1 - - [22/Mar/2015:18:13:43 +0000] "PUT /v1/repositories/test/ HTTP/1.1" 200 2 "-" "docker/1.5.0 go/go1.4.1 git-commit/a8a31ef kernel/3.16.0-30-generic os/linux arch/amd64"
172.17.42.1 - - [22/Mar/2015:18:13:44 +0000] "GET /v1/images/77ea55b60d7fb110ea7890ab711f19b7b28a6893f9c3ec68706dc123a8717e88/json HTTP/1.1" 400 49 "-" "docker/1.5.0 go/go1.4.1 git-commit/a8a31ef kernel/3.16.0-30-generic os/linux arch/amd64"
172.17.42.1 - - [22/Mar/2015:18:13:44 +0000] "GET /v1/images/511136ea3c5a64f264b78b5433614aec563103b4d4702f3ba7d4d2698e22c158/json HTTP/1.1" 200 483 "-" "docker/1.5.0 go/go1.4.1 git-commit/a8a31ef kernel/3.16.0-30-generic os/linux arch/amd64"
172.17.42.1 - - [22/Mar/2015:18:13:45 +0000] "GET /v1/images/82fed95f99a4ce9a14c73dae9118b2b4f13972a026fc157675e77bf651e7c0b9/json HTTP/1.1" 404 28 "-" "docker/1.5.0 go/go1.4.1 git-commit/a8a31ef kernel/3.16.0-30-generic os/linux arch/amd64"
172.17.42.1 - - [22/Mar/2015:18:13:45 +0000] "GET /v1/images/1dc2bd013af7f9c67b57e120fef34981fc7888b170342b1b24d7b60a11d48a44/json HTTP/1.1" 404 28 "-" "docker/1.5.0 go/go1.4.1 git-commit/a8a31ef kernel/3.16.0-30-generic os/linux arch/amd64"
172.17.42.1 - - [22/Mar/2015:18:13:45 +0000] "GET /v1/images/e87e60fb21f0404ca05580f7c154310b962c9ace68737cd2a67b4afbff1cb7da/json HTTP/1.1" 404 28 "-" "docker/1.5.0 go/go1.4.1 git-commit/a8a31ef kernel/3.16.0-30-generic os/linux arch/amd64"
172.17.42.1 - - [22/Mar/2015:18:13:45 +0000] "GET /v1/images/59a878f244f6236150422f8a1df375f7342122d4559440063e599b9f728890a1/json HTTP/1.1" 404 28 "-" "docker/1.5.0 go/go1.4.1 git-commit/a8a31ef kernel/3.16.0-30-generic os/linux arch/amd64"
172.17.42.1 - - [22/Mar/2015:18:13:46 +0000] "GET /v1/images/d25fa3af9233de6da3deb63794a689510698aefc1ad36d97d93e7ea5d133c613/json HTTP/1.1" 404 28 "-" "docker/1.5.0 go/go1.4.1 git-commit/a8a31ef kernel/3.16.0-30-generic os/linux arch/amd64"
172.17.42.1 - - [22/Mar/2015:18:13:46 +0000] "GET /v1/images/7e9014d6a4104b769792a8730d94f210d52569764fb84bca53f2c460ccf4937a/json HTTP/1.1" 404 28 "-" "docker/1.5.0 go/go1.4.1 git-commit/a8a31ef kernel/3.16.0-30-generic os/linux arch/amd64"
172.17.42.1 - - [22/Mar/2015:18:13:46 +0000] "GET /v1/images/96246f4a9f8eba22228ba4bb52fcab6c19f47ca4ec720b0f7659c8df427f5958/json HTTP/1.1" 404 28 "-" "docker/1.5.0 go/go1.4.1 git-commit/a8a31ef kernel/3.16.0-30-generic os/linux arch/amd64"
172.17.42.1 - - [22/Mar/2015:18:13:46 +0000] "GET /v1/images/d35bb0b9153d4ed64ec0b4c462d78e08f824a61333137056a68174fdd39e221c/json HTTP/1.1" 404 28 "-" "docker/1.5.0 go/go1.4.1 git-commit/a8a31ef kernel/3.16.0-30-generic os/linux arch/amd64"
172.17.42.1 - - [22/Mar/2015:18:13:46 +0000] "GET /v1/images/8a4274e9502f358a3afd194af2532dd568ecd2361597548aa70a2c396c56134e/json HTTP/1.1" 404 28 "-" "docker/1.5.0 go/go1.4.1 git-commit/a8a31ef kernel/3.16.0-30-generic os/linux arch/amd64"
172.17.42.1 - - [22/Mar/2015:18:13:47 +0000] "GET /v1/images/1877256351bf4956cf0aa7af50e3fe0331fe821f3bc63cdde0a7c55861dce206/json HTTP/1.1" 404 28 "-" "docker/1.5.0 go/go1.4.1 git-commit/a8a31ef kernel/3.16.0-30-generic os/linux arch/amd64"
172.17.42.1 - - [22/Mar/2015:18:13:47 +0000] "GET /v1/images/76aebbf160b6a2328d3ea2e83383f1e8401a5ea79f4af8200d73b65cef62b54a/json HTTP/1.1" 404 28 "-" "docker/1.5.0 go/go1.4.1 git-commit/a8a31ef kernel/3.16.0-30-generic os/linux arch/amd64"
172.17.42.1 - - [22/Mar/2015:18:13:47 +0000] "GET /v1/images/4f6b70c73446d31dbf2a6bce7540fa7457db4da990c8bde0f6210c17c3c3f4f3/json HTTP/1.1" 404 28 "-" "docker/1.5.0 go/go1.4.1 git-commit/a8a31ef kernel/3.16.0-30-generic os/linux arch/amd64"
172.17.42.1 - - [22/Mar/2015:18:13:47 +0000] "GET /v1/images/9890c0c7acc5424cbb8e80c5e489985139076f2b31a23ef90ddc90b8ea6d584d/json HTTP/1.1" 404 28 "-" "docker/1.5.0 go/go1.4.1 git-commit/a8a31ef kernel/3.16.0-30-generic os/linux arch/amd64"
172.17.42.1 - - [22/Mar/2015:18:13:47 +0000] "GET /v1/images/d195ebaa16b0157e07b2e348e5dc5f7abfa8d3f109fc6ddd573dac4921de30d6/json HTTP/1.1" 404 28 "-" "docker/1.5.0 go/go1.4.1 git-commit/a8a31ef kernel/3.16.0-30-generic os/linux arch/amd64"
172.17.42.1 - - [22/Mar/2015:18:13:48 +0000] "GET /v1/images/cc310e65c4d620c74276ff866f3e46052cc4a09a005a95fa02df0fab9c4083a1/json HTTP/1.1" 404 28 "-" "docker/1.5.0 go/go1.4.1 git-commit/a8a31ef kernel/3.16.0-30-generic os/linux arch/amd64"
172.17.42.1 - - [22/Mar/2015:18:13:48 +0000] "GET /v1/images/f0f08063ec00a94044843d0f9a27fafad15080e85e0aa412c5fdad0768b536f8/json HTTP/1.1" 404 28 "-" "docker/1.5.0 go/go1.4.1 git-commit/a8a31ef kernel/3.16.0-30-generic os/linux arch/amd64"
172.17.42.1 - - [22/Mar/2015:18:13:48 +0000] "GET /v1/images/f44a1b4af2afd5037a3c1d2d6dd475e6bf3382a40f835070b409233c146c1e5c/json HTTP/1.1" 404 28 "-" "docker/1.5.0 go/go1.4.1 git-commit/a8a31ef kernel/3.16.0-30-generic os/linux arch/amd64"
172.17.42.1 - - [22/Mar/2015:18:13:48 +0000] "GET /v1/images/def4ffaca919d6badfe27a3344a80d8e1d09baf7c733acf523872942b2d50717/json HTTP/1.1" 404 28 "-" "docker/1.5.0 go/go1.4.1 git-commit/a8a31ef kernel/3.16.0-30-generic os/linux arch/amd64"
172.17.42.1 - - [22/Mar/2015:18:13:48 +0000] "GET /v1/images/3d842a358e9d060bc9720a9410407d50c1a0e3514e9db4910781e58f91386587/json HTTP/1.1" 404 28 "-" "docker/1.5.0 go/go1.4.1 git-commit/a8a31ef kernel/3.16.0-30-generic os/linux arch/amd64"
172.17.42.1 - - [22/Mar/2015:18:13:49 +0000] "GET /v1/images/2946c3fe9946b343410e1f129dae8ffb9032066ebb06d09f8bcc4db07cf8a148/json HTTP/1.1" 404 28 "-" "docker/1.5.0 go/go1.4.1 git-commit/a8a31ef kernel/3.16.0-30-generic os/linux arch/amd64"
172.17.42.1 - - [22/Mar/2015:18:13:49 +0000] "GET /v1/images/80ab374fa1158a46d08e979b51b7efb165f636555dc7cb29e91599f1fa23bdc9/json HTTP/1.1" 404 28 "-" "docker/1.5.0 go/go1.4.1 git-commit/a8a31ef kernel/3.16.0-30-generic os/linux arch/amd64"
172.17.42.1 - - [22/Mar/2015:18:13:51 +0000] "PUT /v1/images/77ea55b60d7fb110ea7890ab711f19b7b28a6893f9c3ec68706dc123a8717e88/json HTTP/1.1" 200 4 "-" "docker/1.5.0 go/go1.4.1 git-commit/a8a31ef kernel/3.16.0-30-generic os/linux arch/amd64"
2015-03-22 18:14:44,967 ERROR: Exception on /v1/images/77ea55b60d7fb110ea7890ab711f19b7b28a6893f9c3ec68706dc123a8717e88/layer [PUT]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/toolkit.py", line 280, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/toolkit.py", line 37, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/images.py", line 222, in put_image_layer
    store.stream_write(layer_path, sr)
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/drivers/s3.py", line 144, in stream_write
    raise e
error: [Errno 32] Broken pipe
22/Mar/2015:18:14:44 +0000 ERROR: Exception on /v1/images/77ea55b60d7fb110ea7890ab711f19b7b28a6893f9c3ec68706dc123a8717e88/layer [PUT]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/toolkit.py", line 280, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/toolkit.py", line 37, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/images.py", line 222, in put_image_layer
    store.stream_write(layer_path, sr)
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/drivers/s3.py", line 144, in stream_write
    raise e
error: [Errno 32] Broken pipe
172.17.42.1 - - [22/Mar/2015:18:14:44 +0000] "PUT /v1/images/77ea55b60d7fb110ea7890ab711f19b7b28a6893f9c3ec68706dc123a8717e88/layer HTTP/1.1" 500 291 "-" "docker/1.5.0 go/go1.4.1 git-commit/a8a31ef kernel/3.16.0-30-generic os/linux arch/amd64"

**Comment by dmp42** [comment]
What version of the registry is this?

**Comment by aviz** [comment]
0.9.1 from docker hub

**Comment by fengler** [comment]
#dibs
